version: '2'

services:
  spark-master:
    image: bitnami/spark:3.1.3-debian-11-r0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - .:/app
      - ./spark_conf/sparkdef.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - '127.0.0.1:8080:8080'

  spark-worker-1:
    image: bitnami/spark:3.1.3-debian-11-r0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - .:/app

  spark-driver:
    image: spark-drive-streamlit #bitnami/spark:3.1.3-debian-11-r0
    volumes:
      - .:/app
    command: tail -f /dev/null
    user: root
    working_dir: /app
    environment:
      PYTHONPATH: /opt/bitnami/spark/python:/opt/bitnami/spark/python/lib/py4j-0.10.9-src.zip
#    links:
#      - mongodb:mongodb
    expose:
      - 8501
    ports:
      - 8501:8501

  mongodb:
    image: mongo
    expose:
      - 27017
    volumes:
      #- ~/Users/philippheitmann/Desktop/docker_test/data/mongo_db:/data/db
      - ./data/mongo_db:/data/db
      #- ~/Volumes/Dateien/Coding/Datasets/Flight_Data/mongo_db:/data/db
    ports:
      - 27017:27017
