#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import pandas as pd
import numpy as np
from TravelDashboard.data import preproc_flight_data, get_data, save_processed_data



if __name__ == "__main__":
    #Load data
    flights, opensky_DB, seat_data, aircraftregister_US, response = get_data()

    # Preprocess flight data
    pflights_df_final = preproc_flight_data(flights, opensky_DB, seat_data,
                                            aircraftregister_US)

    # Store preprocessed DataFrame to csv
    save_processed_data(pflights_df_final, response)
